fname = input("Enter First Name: ")
lname = input("Enter Last Name: ")
mname = input("Enter Middle Name: ")
bday = input("Enter Birthday: ")
gender = input("Enter Gender: ")
address = input("Enter Address: ")
course = input("Enter Course Name: ")
yrlvl = input("Enter Year Level: ")

print("----------------------------------------")
print("My first name is: ", fname)
print("My last name is: ", lname)
print("My middle name is: ", mname)
print("My birthday is: ", bday)
print("My gender is: ", gender)
print("My address is: ", address)
print("My course name is: ", course)
print("My year level is: ", yrlvl)
print("----------------------------------------")